### PR TITLE
Add icon sets

### PR DESCRIPTION
**Pull request by sbrin**
Add icon sets
Add @gaai icons

### CODE REVIEW

**Comment by Gaai** [comment]
> @Gaai there is an issue with icons size :) Our script expects the file name to contain icons size in form of WIDTHxHEIGHT (it is strictly required)
> 
> But in your icons it is different like HEIGHTxWIDTH
> 
> Is it possible for you to change the size formatting?
> 
> Also please check how it works [feature-add-icon-sets.lopaka-dev.pages.dev](https://feature-add-icon-sets.lopaka-dev.pages.dev/)

Yes I know. "btw the no of pixels in the filesnames are wrong way around so: y - x. Perhaps a batch rename of that to x-y would make sense. I did it for sorting perposes." Is the message I added to the zip files in the forum. Did I see you renaimed them already? A simple regex batch rename would work. I could do it too.

**Comment by Gaai** [comment]
Guess they should be inverted too? So they are displayed with the orange background?

**Comment by Gaai** [comment]
I've put the new zipfile up. In the original discussion thread. Batch renamed x-y width-hight and also inverted.

**Comment by sbrin** [comment]
The transparent is much handy from my perspective. Thank you, I've just pushed the update. Check the link https://feature-add-icon-sets.lopaka-dev.pages.dev/

Yep, we lost drag and drop in last november, but I'm sure it will be back soon

**Comment by Gaai** [comment]
> The transparent is much handy from my perspective. Thank you, I've just pushed the update. Check the link [feature-add-icon-sets.lopaka-dev.pages.dev](https://feature-add-icon-sets.lopaka-dev.pages.dev/)
Nice. Transparent it is. I've got a bunch more waiting, that I hadn't cropped yet. Would it be possible to add/modify myself in the future? Probably will be updating some more coming weeks.

**Comment by sbrin** [comment]
> > The transparent is much handy from my perspective. Thank you, I've just pushed the update. Check the link [feature-add-icon-sets.lopaka-dev.pages.dev](https://feature-add-icon-sets.lopaka-dev.pages.dev/)
> 
> Nice. Transparent it is. I've got a bunch more waiting, that I hadn't cropped yet. Would it be possible to add/modify them myself in the future? Probably will be updating some more coming weeks.

Sure, you can check this MR changes. Just put image in proper folder and add it to list in `src/icons/gaai.ts`

**Pull request merged**
