### PR TITLE
release v0.4

### PR DESCRIPTION
**Pull request by sbrin**
**New Features:**

**Interactive Editor Support**: The editor now supports interaction across all platforms, with improved source code parameters parsing and cursor position preservation.

- Select layers when you click on a source code line, highlighting source code lines for active layer
- Source code optimization: removing duplicate images, font and color declarations
- Source code highlighting using ACE

**BDF Font Support**: Dynamic loading and rendering of BDF fonts have been integrated, optimizing the compiled font size and ensuring correct text rendering as per specifications.

**Image operations**: Rotate, mirror, invert paint and image layers. Merge any layers into a single drawing. Download image as PNG.

**Source code settings**
Different code styles for Arduino and ESP_IDF. Enable/disable PROGMEM declaration. Wrap code in a single draw() function.

**U8g2 XOR "inverse" mode**
Set any layer to render as XOR bitmap.

**Enhancements:**

- Ability to change the order of layers using drag and drop
- Updated Dockerfile for better deployment.
- Colored images (the same as paint layers)

### CODE REVIEW

**Comment by Gaai** [comment]
Imported images aren't rendered correctly. Other updates looking promising btw, with idf support and image tools!!!
Got some new icons coming too.

**Comment by sbrin** [comment]
> Imported images aren't rendered correctly. Other updates looking promising btw, with idf support and image tools!!! Got some new icons coming too.

Thanks! Can you share more details regarding images? a screenshot or video recording would be cool

**Comment by Gaai** [comment]
screenshot-2024-02-23 180533

**Comment by deadlink** [comment]
@Gaai share me this icon please, i will check

**Comment by Gaai** [comment]
cards_spades_15x16
It happens with any icon. Not sure if this is the best image to check what's happening.

**Comment by Gaai** [comment]
Added a pull request for some new icons I made recently.

**Comment by deadlink** [comment]
image
I couldn't reproduce on the latest version

**Comment by Gaai** [comment]
Let me check. Is this version you tried the version linked in here?

**Comment by Gaai** [comment]
https://68533a75.lopaka-dev.pages.dev/

**Comment by Gaai** [comment]
And happens also on https://dev.lopaka.app/ for me

**Comment by Gaai** [comment]
Alright. So I checked in an other browser. In MS Edge it works alright in both versions. In brave it doesn't. Maybe a cache issue. But got to go, so can only check later this evening.

**Comment by Gaai** [comment]
Works in Chrome too.

**Comment by Gaai** [comment]
So I've checked again, and the problem persists. On Firefox it's even worse. The preview / canvas doesn't render right even at start. Just vertical colored bars that swap places. 
On brave the issue seems to be with uploaded images. Adding icons from the list works fine, also the page loads just fine. Haven't checked to thoroughly but that was my impression. 
Here are the screenshots. Brave freshly installed on different computer. Firefox updated to latest version. Both windows. 
dev_lopaka_firefox2

**Comment by deadlink** [comment]
@Gaai I can't reproduce the issue in Firefox, but I have investigated the issue in Brave.
And looks like it is a bug in the Brave. 
Look at this 

Screenshot 2024-02-24 at 18 44 31

These are the colors I got from that image in Brave... and... this is false because the image only has black and white pixels, I checked it manually.

I understand that the colors are quite close to black and white, but our algorithm is not so complex to take this into account

I can try to solve this in the future and improve the algorithm, but at the moment it’s more of a browser bug

**Comment by Gaai** [comment]
Might be a privacy setting on Firefox then too. I'll check later if I can change some of those to test.

**Review by deadlink — COMMENTED** [review]
No critical issues found, can be merged after adding #126

**Pull request merged**
