### PR TITLE
Correct hand x dimension

### PR DESCRIPTION
**Pull request by Gaai**
two icons had wrong width again ;)

### CODE REVIEW

**Comment by Gaai** [comment]
Yes I suggested the same thing. Think we all agree that's better. I've noticed it's real easy to get it wrong, especially since when I'm designing I'll often work with multiple revisions. Sometimes forget to update the width accordingly. Haha.

**Comment by sbrin** [comment]
@deadlink good idea. At the same time we have a custom imags which works without explicit namings :) Maybe use the same approach?

**Comment by deadlink** [comment]
@sbrin I don't think so since we need to sort the icons by size, but the size can only be obtained after the image is loaded

**Comment by Gaai** [comment]
@deadlink why do you need to order by size? I'd wish they could be ordered alphabetically. That way icons of the same category would be grouped together an you can easily find them. I've named them especially for that.

**Comment by deadlink** [comment]
#107

**Pull request merged**
