### PR TITLE
Add more icons

### PR DESCRIPTION
**Pull request by Gaai**
remove duplicate, rename battery_full_2 for consistency

### CODE REVIEW

**Comment by Gaai** [comment]
Is this the most practical way that I can make a pull request for you? I've updated the icons and the gaai.ts file like you suggested. Perhaps I could rename the icons in a way that they are grouped in categories better. But perhaps you've got another idea. Just let me know.

**Comment by sbrin** [comment]
@Gaai could you please resolve the conflicts? I guess you can force your changes

**Comment by Gaai** [comment]
@sbrin `Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.`?

**Comment by sbrin** [comment]
https://github.com/sbrin/lopaka/pull/97

**Pull request closed without merging**
